# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('bank_account_type', models.TextField()),
                ('account_class', models.TextField(db_column='class')),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('enable_payments_to_account', models.BooleanField()),
                ('has_attachments', models.BooleanField()),
                ('reporting_code', models.TextField()),
                ('show_in_expense_claims', models.BooleanField()),
                ('status', models.TextField()),
                ('tax_type', models.TextField()),
                ('type', models.TextField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('journal_date', models.DateTimeField()),
                ('journal_number', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('reference', models.TextField()),
                ('source_id', models.TextField()),
                ('source_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('tax_type', models.TextField()),
                ('tax_name', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xero.Account')),
                ('activities', models.ManyToManyField(to='xero.Activity')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='xero.Journal')),
            ],
        ),
    ]
